### PR TITLE
Don't print warning if lift is going to same floor

### LINKED ISSUE #17: Make busy lift terminal output less threatening
A followup from this discussion: https://github.com/open-rmf/rmf/discussions/40#discussioncomment-677772

It would be nice if the message that gets outputted by the lift when it's busy carrying out a task could be reworked so that it doesn't lead users to think that something is wrong. We could reword it, or we could remove it altogether when the incoming requests perfectly matches the current request.

We could also consider revising the lift supervisor so that it doesn't duplicate this request message.

### PR DESCRIPTION
**Pull request by luca-della-vedova**
### Fixed bug

Closes #17, now the warning is only printed if the new request is different from the previous one.

This should reduce terminal printouts in scenarios with lift activity, previously the printed error might have misled the users into thinking something was wrong.

### CODE REVIEW

File: rmf_building_sim_common/src/lift_common.cpp [hunk 1]
```diff
@@ -225,11 +225,18 @@ LiftCommon::LiftCommon(rclcpp::Node::SharedPtr node,
...
       {
-        RCLCPP_INFO(logger(),
-        "Failed to request: [%s] is busy at the moment",
-        _lift_name.c_str());
+        if (_lift_request->destination_floor != msg->destination_floor ||
+        _lift_request->request_type != msg->request_type ||
+        _lift_request->session_id != msg->session_id)
+        {
+          RCLCPP_INFO(logger(),
+          "Failed to request: [%s] is busy at the moment",
```
Comment (mxgrey) [inline rmf_building_sim_common/src/lift_common.cpp:237]: Maybe we shouldn't say "Failed" since that usually implies something is not working as intended.

Maybe say "Blocking request" or "Discarding request" instead?

**Review by Yadunund — APPROVED** [review]

**Review by Yadunund — APPROVED** [review]
