### PR TITLE
Finish rename of nonholonomic to ackermann, make ackermann vehicles standardized with RMF stack

### LINKED ISSUE #47: Unify ackermann and diff_drive plugins to be compatible with RMF
### Description

Make ackermann vehicles compatible with RMF.

### Implementation considerations

Right now vehicles with ackermann steering can't be controlled by RMF since `slotcar` subscribes to a different topic than the one used by the rest of the stack (`ackmann_path_requests` vs `robot_path_requests`).
As such, slotcar for ackermann type vehicles will ignore any path request sent to `robot_path_requests`.

### Alternatives

Since for now both the topics expect the same data type, the simplest way to deal with the issue would be to subscribe to `robot_path_request` then when a message is received, depending on the vehicle type, execute what is now in the ackmann callback or the normal path request callback.
There might still be need for some work to get a solid RMF ackermann implementation such as:

- Make sure the slotcar ackermann plugin respects time (i.e. if RMF schedules a wait at a certain waypoint, the vehicle should stop and wait).
- Add support at the `rmf_traffic` level, by implementing appropriate `rmf_traffic::agv::Interpolate` and `rmf_traffic::agv::VehicleTraits`.

But at least this change should get a minimal implementation up.

### LINKED ISSUE #48: Ackermann vehicles don't report their state
### Required information:

Ubuntu 20.04, on Galactic - RMF Source build

### Description of the bug

Vehicles with Ackermann steering don't report their state in a ROS2 topic, hence making it impossible for downstream users to know / display their position.

### Steps to reproduce the bug

Run a simulation with ackermann steering vehicles:

`ros2 launch rmf_demos_ign test_ackmann.launch.xml`

Then check the `/robot_state` topic in another terminal:

`ros2 topic echo /robot_state`

### Expected behavior

The state of the robots is reported.

### Actual behavior

Nothing is published

### Additional information

It seems that in the design of the `update_nonholonomic` function the `publish_robot_state(time)` call was not included.

### PR DESCRIPTION
**Pull request by luca-della-vedova**
### Fixed bug

Closes #47 and closes #48.
Ackermann vehicles were using custom topics for path requests (even though they use the same data format as normal robots), as well as not reporting their state hence making it impossible for downstream users to monitor them. This PR fixes both the issues, as well as finishing the renaming of nonholonomic -> ackermann drive and cleaning up the code a bit.

To test, with the matching PR in rmf_demos:

`ros2 launch rmf_demos_ign test_ackman.launch.xml`

And

`ros2 run rmf_demos_tasks request_ackmann_path -p rmf_demos_maps -n maps/test_ackman/nav_graphs/0.yaml -s a1 -e c1 -i task11 -r ambulance`

### CODE REVIEW

**Review by ddengster — APPROVED** [review]
tested with the new changes on https://github.com/open-rmf/rmf_demos/pull/86, LGTM!

File: rmf_robot_sim_common/include/rmf_robot_sim_common/slotcar_common.hpp [hunk 1]
```diff
@@ -130,6 +130,13 @@ enum class SteeringType
 class SlotcarCommon
 {
 public:
+  typedef struct UpdateResult
```
Comment (aaronchongth) [inline rmf_robot_sim_common/include/rmf_robot_sim_common/slotcar_common.hpp:133]: Nit: Just `struct` would be alright, we should move towards modern C++ with the rest of the RMF codebase

File: rmf_robot_sim_common/include/rmf_robot_sim_common/slotcar_common.hpp [hunk 2]
```diff
@@ -317,7 +310,10 @@ class SlotcarCommon
 
   void path_request_cb(const rmf_fleet_msgs::msg::PathRequest::SharedPtr msg);
 
-  void ackmann_path_request_cb(
+  void diff_drive_path_request_cb(
```
Comment (aaronchongth) [inline rmf_robot_sim_common/include/rmf_robot_sim_common/slotcar_common.hpp:313]: Nit: since we are not exactly using these functions as a callback, we should call it something like `handle_diff_drive_path_request` or something along those lines.

File: rmf_robot_sim_common/src/slotcar_common.cpp [hunk 3]
```diff
@@ -192,15 +182,31 @@ void SlotcarCommon::path_request_cb(
...
+  {
+    case SteeringType::DIFF_DRIVE:
+      diff_drive_path_request_cb(msg);
+      break;
+    case SteeringType::ACKERMANN:
+      ackermann_path_request_cb(msg);
+      break;
+    default:
+      break;
+      // NOOP
```
Comment (aaronchongth) [inline rmf_robot_sim_common/src/slotcar_common.cpp:196]: Nit: Unused comment.

File: rmf_robot_sim_common/src/slotcar_common.cpp [hunk 4]
```diff
@@ -621,33 +629,33 @@ std::pair<double, double> SlotcarCommon::update(const Eigen::Isometry3d& pose,
...
     const auto goal_heading = compute_heading(trajectory.back());
-    displacements.second = compute_change_in_rotation(
+    result.w = compute_change_in_rotation(
       current_heading,
       goal_heading);
 
     // Put in a deadzone if yaw is small enough. This essentially locks the
     // tires. COMMENTED OUT as it breaks rotations for some reason...
-    // if(std::abs(displacements.second) < std::max(0.1*M_PI/180.00, goal_yaw_tolerance))
+    // if(std::abs(result.w) < std::max(0.1*M_PI/180.00, goal_yaw_tolerance))
```
Comment (aaronchongth) [inline rmf_robot_sim_common/src/slotcar_common.cpp:653]: Should there be a follow up to this? If so, we should add a TODO comment, otherwise, remove commented out code.

File: rmf_robot_sim_common/src/slotcar_common.cpp [hunk 5]
```diff
@@ -724,22 +732,22 @@ std::pair<double, double> SlotcarCommon::update_nonholonomic(
...
+      result.w = cross < 0.0 ? -acos(dotp) : acos(dotp);
     }
     else
-      displacements.second = 0.0;
+      result.w = 0.0;
 
-    // printf("_nonholonomic_traj_idx %d dpos_mag: %g displacements %g, %g\n",
-    //   _nonholonomic_traj_idx, dpos_mag, displacements.first, displacements.second);
+    // printf("_ackermann_traj_idx %d dpos_mag: %g displacements %g, %g\n",
+    //   _ackermann_traj_idx, dpos_mag, result.v, result.w);
```
Comment (aaronchongth) [inline rmf_robot_sim_common/src/slotcar_common.cpp:741]: Nit: remove unused comments

File: rmf_robot_sim_common/src/slotcar_common.cpp [hunk 6]
```diff
@@ -457,23 +448,40 @@ std::string to_str(uint32_t type)
...
+  switch (this->_steering_type)
+  {
+    case SteeringType::DIFF_DRIVE:
+      return update_diff_drive(pose, obstacle_positions, time);
+    case SteeringType::ACKERMANN:
+      // TODO(anyone) use obstacle_positions for emergency stop for ackermann
+      return update_ackermann(pose, obstacle_positions, time);
+    default:
+      return UpdateResult();
+      // NOOP
```
Comment (aaronchongth) [inline rmf_robot_sim_common/src/slotcar_common.cpp:467]: Nit: redundant comment

**Review by aaronchongth — CHANGES_REQUESTED** [review]
Looks great! Thanks for the changes, I just have a few minor comments.

**Comment by Yadunund** [comment]
Apart from @aaronchongth 's comments, the changes look okay. I would be cool to have a `full control` ackermann vehicle in `rmf_demos` in the future. Right now if I try to start up a `full control` fleet adapter to control the ackermann steered vechile, the `PathRequest` msg submitted by the fleet adapter will contain in-place rotations which are not filtered out on the `slotcar` end. We could implement some filtering in the future or better yet update `rmf_traffic` to interpolate waypoints for such vehicles  such that the waypoints in the `PathRequest` respect the ackermann constraints. I've opened a ticket for that https://github.com/open-rmf/rmf_traffic/issues/42

File: rmf_robot_sim_common/src/slotcar_common.cpp (hunk 4 above)
Comment (luca-della-vedova) [reply rmf_robot_sim_common/src/slotcar_common.cpp]: Not sure it's been there since forever, since it seems not to cause any issue will just delete it.

**Comment by luca-della-vedova** [comment]
Addressed all the changes! I also found a few areas for small cleanups.

> Apart from @aaronchongth 's comments, the changes look okay. I would be cool to have a `full control` ackermann vehicle in `rmf_demos` in the future. Right now if I try to start up a `full control` fleet adapter to control the ackermann steered vechile, the `PathRequest` msg submitted by the fleet adapter will contain in-place rotations which are not filtered out on the `slotcar` end. We could implement some filtering in the future or better yet update `rmf_traffic` to interpolate waypoints for such vehicles such that the waypoints in the `PathRequest` respect the ackermann constraints. I've opened a ticket for that [open-rmf/rmf_traffic#42](https://github.com/open-rmf/rmf_traffic/issues/42)

Agreed! I think it would be a great new feature to have. For our specific scenario we are not too concerned with this issue yet so I think it's fine to take time to do a good implementation on the `rmf_traffic` side rather than a quick patch on slotcar to filter waypoints.

**Review by Yadunund — APPROVED** [review]
LGTM

**Review by aaronchongth — APPROVED** [review]
Thanks for the changes, LGTM
